name: Run Unit and Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    env:
      DB_TYPE: "mysql"
      DB_HOST: "localhost"
      DB_PORT: "3306"
      DB_NAME: "test_db"
      DB_USER: "test_user"
      DB_PASSWORD: "test_pass"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pytest

      - name: Run Unit Tests
        env:
          PYTHONPATH: ${{ github.workspace }} # TODO: Is this needed long-term?
        run: |
          source venv/bin/activate
          pytest -m unit

  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    needs: unit-tests

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: test_pass
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_pass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root --password=test_pass"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_TYPE: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_NAME: test_db
      DB_USER: test_user
      DB_PASSWORD: test_pass

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pytest pymysql
      
      - name: Install Data Loader CLI
        run: |
          source venv/bin/activate
          pip install -e .

      - name: Wait for MySQL to Be Ready
        run: |
          for i in {30..0}; do
            if mysql -h 127.0.0.1 -u$DB_USER -p$DB_PASSWORD -e "SELECT 1" $DB_NAME > /dev/null 2>&1; then
              echo "MySQL is ready!"
              break
            fi
            echo "Waiting for MySQL to be ready..."
            sleep 2
          done

      - name: Initialize Database Schema
        run: |
          mysql -h 127.0.0.1 -u$DB_USER -p$DB_PASSWORD $DB_NAME < config/schema.sql
          echo "Test database schema initialized!"

      - name: Run Integration Tests
        env:
          PYTHONPATH: ${{ github.workspace }} # TODO: Is this needed long-term?
        run: |
          source venv/bin/activate
          pytest -m integration